<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Newsletter Durango Duarte Channel</title>
    </head>
    <body>

        <?php
        $meses = array(
            '1' => 'Janeiro',
            '2' => 'Fevereiro',
            '3' => 'Mar&ccedil;o',
            '4' => 'Abril',
            '5' => 'Maio',
            '6' => 'Junho',
            '7' => 'Julho',
            '8' => 'Agosto',
            '9' => 'Setembro',
            '10' => 'Outubro',
            '11' => 'Novembro',
            '12' => 'Dezembro'
        );
        $d = date('d', strtotime($envio[0]['dtDataCadastro']));
        $m = (int) date('m', strtotime($envio[0]['dtDataCadastro']));
        $a = date('Y', strtotime($envio[0]['dtDataCadastro']));
        $dataToda = 'Manaus, ' . $d . ' de ' . $meses[$m] . ' de ' . $a;
        ?>
        <table style="margin: 0 auto; padding: 0 auto; border: 0; border-collapse: collapse; border-spacing: 0; font-family: arial, sans-serif; font-size: 14px; width: 100%; max-width: 600px;">
            <tr border="0">
                <th border="0" colspan="2" style="background: url(<?php echo $url_raiz; ?>img/bg-top.png);">
                    <a style="display: block; padding: 30px 0;" title="<?php echo $this->_geralConfig[0]["nmTituloSite"]; ?>" href="<?php echo $url_raiz; ?>">
                        <img style="border: 0; display: block; width: 100%; max-width: 285px; margin: 0 auto; padding: 0;" alt="<?php echo $this->_geralConfig[0]["nmTituloSite"]; ?>" src="<?php echo $url_raiz; ?>img/<?php echo $this->_geralConfig[0]["nmLinkLogoTopo"]; ?>" />
                    </a>
                </th>
            </tr>

            <tr style="background: #29abe2; color: #fff;" border="0">
                <td style="padding: 15px;" border="0">
                    <b>Newsletter n&ordm;.:</b> <?php printf('%04d', $envio[0]['numeroEnvio']); ?>/<?php echo $a; ?>
                </td>
                <td style="text-align: right; padding: 15px;" border="0">
                    <?php echo $dataToda; ?>
                </td>
            </tr>

            <?php
            $ine = 0;
            foreach ($envio as $noticia) {
                $ine++;
                ?>
                <?php
                if (vazio($noticia['nmLinkImagem'])) {
                    $imgDestaque = $url_raiz . 'img/' . ($noticia['nmLinkImagem'] = 'blank-300.jpg');
                } else {
                    $imgDestaque = $url_raiz . 'arquivos/enviados/image/' . $noticia['nmLinkImagem'];
                }
                ?>
                <?php if ($ine % 2 != 0) { ?>

                    <tr border="0">
                        <td border="0" colspan="2">
                            <table style="margin: 0 auto; padding: 0; border: 0; border-collapse: collapse; border-spacing: 0; font-family: arial, sans-serif; font-size: 14px; width: 100%;">
                                <tr border="0">
                                    <td border="0" style="padding-top: 15px; width: 35%;">
                                        <?php if ($imgDestaque) { ?>
                                            <a style="display: block;" title="<?php echo stripslashes($noticia['nmTituloConteudo']); ?>" target="_blank" href="<?php echo $url_raiz; ?>noticias/<?php echo $noticia['nmTituloAmigavel']; ?>">
                                                <img style="border: 0; display: block; height: auto; width: 100%;" src="<?php echo $imgDestaque; ?>" />
                                            </a>
                                        <?php } ?>
                                    </td>
                                    <td border="0" style="padding: 15px; width: 65%;">
                                        <h2 style="margin: 0 0 15px; padding: 0; font-size: 18px;">
                                            <a style="color: #333; text-decoration: none;" target="_blank" href="<?php echo $url_raiz; ?>noticias/<?php echo $noticia['nmTituloAmigavel']; ?>">
                                                <?php echo stripslashes($noticia['nmTituloConteudo']); ?>
                                            </a>
                                        </h2>

                                        <p style="color: #666; line-height: 150%; text-align: justify;">
                                            <?php echo resume(strip_tags(stripslashes($noticia['nmConteudo'])), 200); ?>
                                            <a style="color: #29abe2; font-weight: bold; text-decoration: none;" target="_blank" href="<?php echo $url_raiz; ?>noticias/<?php echo $noticia['nmTituloAmigavel']; ?>">Veja no site.</a>
                                        </p>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                <?php } else { ?>

                    <tr border="0">
                        <td border="0" colspan="2">
                            <table style="margin: 0 auto; padding: 0; border: 0; border-collapse: collapse; border-spacing: 0; font-family: arial, sans-serif; font-size: 14px; width: 100%;">
                                <tr border="0">
                                    <td border="0" style="padding: 15px; width: 65%;">
                                        <h2 style="margin: 0 0 15px; padding: 0; font-size: 18px;">
                                            <a style="color: #333; text-decoration: none;" target="_blank" href="<?php echo $url_raiz; ?>noticias/<?php echo $noticia['nmTituloAmigavel']; ?>">
                                                <?php echo stripslashes($noticia['nmTituloConteudo']); ?>
                                            </a>
                                        </h2>

                                        <p style="color: #666; line-height: 150%; text-align: justify;">
                                            <?php echo resume(stripslashes($noticia['nmConteudo']), 200); ?>.
                                            <a style="color: #29abe2; font-weight: bold; text-decoration: none;" target="_blank" href="<?php echo $url_raiz; ?>noticias/<?php echo $noticia['nmTituloAmigavel']; ?>">Veja no site.</a>
                                        </p>
                                    </td>

                                    <td border="0" style="padding-top: 15px; width: 35%;">
                                        <?php if ($imgDestaque) { ?>
                                            <a style="display: block; margin: 0; padding: 0;" title="<?php echo $noticia['nmTituloConteudo']; ?>" target="_blank" href="<?php echo $url_raiz; ?>noticias/<?php echo $noticia['nmTituloAmigavel']; ?>">
                                                <img style="border: 0; display: block; height: auto; max-height: 200px; width: 100%; margin: 0; padding: 0;" src="<?php echo $imgDestaque; ?>" />
                                            </a>
                                        <?php } ?>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                <?php } ?>

                <?php if (count($envio) > ($ine)) { ?>
                    <tr border="0">
                        <td border="0" colspan="2" style="padding-top: 15px;">
                            <hr style="margin: 0; padding: 0; border: none; border-bottom: 1px dotted #ccc; height: 1px; line-height: 1px; width: 100%;">
                        </td>
                    </tr>
                <?php } ?>
            <?php } ?>

            <tr border="0">
                <td border="0" colspan="2" style="padding: 15px 0;">
                    <a style="background: #29abe2; color: #fff; font-weight: bold; text-align: center; text-decoration: none; display: block; padding: 15px;" target="_blank" href="<?php echo $url_raiz; ?>"><?php echo str_replace('http://', '', $url_raiz); ?></a>
                </td>
            </tr>

            <tr border="0">
                <td border="0" colspan="2" style="color: #666; font-size: 10px; line-height: 150%; text-align: center;">
                    Voc&ecirc; est&aacute; recebendo este e-mail porque est&aacute; cadastrado em nossa base de dados!<br/>
                    <a style="border-bottom: 1px dotted; color: #29abe2; text-decoration: none;" target="_blank" href="<?php echo $url_raiz; ?>retirar-email-mala/email/{codEmail}">Clique aqui</a>
                    caso n&atilde;o queira receber mais os nossos e-mails.
                    <br/>
                    E-mail cadastrado: {emailUsuario}.
                    <br/>
                    <strong>Esta &eacute; uma mensagem autom&aacute;tica, por favor n&atilde;o responda.</strong>
                </td>
            </tr>
        </table>

    </body>
</html>